export const platforms = [
  {
    name: "netflix",
    color: "#B6060F",
    image: "/images/netflixlogo.png",
    cover: "/images/netflix-cover.avif",
    series: [
      {
        title: "Stranger Things",
        slug: "stranger-things",
        thumbnail: "/images/strange.jpg",
        desc: "Chlapec se ztratí neznámo kde a město začne odhalovat svoje záhady, mezi které patří i tajné experimenty, děsivě nadpřirozené síly a jedna malá podivná holka.",
        release: "2016",
        categories: ["Drama", "Fantasy", "Horor"],
        cast: ["Winona Ryder", "David Harbour", "Millie Bobby Brown"],
      },
      {
        title: "Narcos",
        slug: "narcos",
        thumbnail: "/images/narcos-thub.jpg",
        desc: "Na konci 70. let dvacátého století se nechvalně proslulý zločinec Pablo Escobar poprvé zapojil do ilegální výroby kokainu. V červenci 1992 se mu podařilo uprchnout z vězení La Catedral, které kolumbijská vláda postavila podle Escobarových vlastních požadavků výměnou za to, že se vzdá úřadům a „odpyká” si tam trest nanejvýše pěti let odnětí svobody. Mezítím se Pablo Escobar stal legendárním drogovým baronem a narkoteroristou. Drsný kriminální seriál Narcos je inspirovaný skutečností a odehrává se v krutém a nemilosrdném světě kolumbisjkých drogových gangů. Jeho hlavním hrdinou je Steve Murphy (Boyd Holbrook). Agent DEA, amerického úřadu pro boj proti drogám, má za úkol dostat Escobara (Wagner Moura) a zničit jeho kartel Medellín. Murphymu pomáhá agent Javier Peña (Pedro Pascal), ale když oba dorazí do Kolumbie, zjišťují, že Escobar má mnohem závažnější problémy než nějakou DEA.",
        release: "2015",
        categories: ["Životopisný", "Krimi", "Drama"],
        cast: ["Pedro Pascal", "Wagner Moura", "Boyd Holbrook"],
      },
      {
        title: "The Queen's Gambit",
        thumbnail: "/images/gambit-thub.jpg",
        slug: "the-queens-gambit",
        desc: "V 50. letech v sobě mladá dívka ze sirotčince objeví mimořádný šachový talent. Její překvapivou cestu ke slávě ale komplikuje boj se závislostí.",
        release: "2020",
        categories: ["Drama"],
        cast: ["Anya Taylor-Joy", "Harry Melling", "Moses Ingram"],
      },
    ],
  },
  {
    name: "disney",
    color: "#171EFF",
    image: "/images/disneyluslogo.png",
    cover: "/images/disney-plus-cover.png",
    series: [
      {
        title: "Secret Invasion",
        thumbnail: "/images/secret-thub.jpg",
        slug: "secret-invasion",
        desc: "V novom seriáli Tajná invázia od Marvelu sa Nick Fury vráti na scénu, keď sa dozvie, že Skrullovia, ktorí dokážu meniť svoju podobu, chystajú na Zemi tajnú inváziu. Fury sa pridá k svojim spojencom, Everettovi Rossovi, Márii Hillovej a Skrullovi Talosovi, ktorý sa usadil na Zemi. Ich úlohou bude zabrániť blížiacej sa skrullskej invázii a zachrániť ľudstvo.",
        release: "2023",
        categories: ["Akční", "Dobrodružný", "Drama"],
        cast: ["Samuel L. Jackson", "Ben Mendelsohn", "Emilia Clarke"],
      },
      {
        title: "Loki",
        slug: "loki",
        thumbnail: "/images/loki-thub.jpg",
        desc: "V novém seriálu Loki od Marvel Studios odehrávajícím se po událostech filmu Avengers: Endgame se nechvalně proslulý bůh lsti a falše Loki vydává na dobrodružnou cestu prostorem a časem.",
        release: "2021",
        categories: ["Akční", "Dobrodružný", "Fantasy"],
        cast: ["Tom Hiddleston", "Sophia Di Martino", "Richard E. Grant"],
      },
      {
        title: "Moon Knight",
        slug: "moon-knight",
        thumbnail: "/images/moon-thub.webp",
        desc: "Steven Grant, bojácný prodavač v obchodě s muzejními suvenýry, trpí výpadky paměti, náměsíčností a vzpomínkami na jiný, cizí život. Steven postupem času zjistí, že trpí mnohočetnou poruchou osobnosti a že sdílí tělo s ostříleným žoldákem Marcem Spectorem. A jak Stevena / Marka pronásleduje stále více nepřátel, musí se vypořádat nejen se svou rozpolcenou osobností, ale i vyřešit smrtonosnou záhadu staroegyptských božstev.",
        release: "2022",
        categories: ["Akční", "Dobrodružný", "Drama"],
        cast: ["Oscar Isaac", "Ethan Hawke", "May Calamawy"],
      },
    ],
  },
  {
    name: "hbomax",
    color: "#902BE8",
    image: "/images/hbomax.webp",
    cover: "/images/hbo-max-cover.jpg",
    series: [
      {
        title: "Game of Thrones",
        slug: "game-of-thrones",
        thumbnail: "/images/game-thub.jpg",
        desc: "Hra o trůny je americký fantasy dramatický seriál kabelové televize HBO. Jeho tvůrci jsou David Benioff a D. B. Weiss. Předlohou je populární, dosud nedokončená fantasy sága Píseň ledu a ohně spisovatele George R. R. Martina, který se na seriálu rovněž podílel. Seriál je pojmenován podle první knihy v sérii.",
        release: "2011",
        categories: ["Akční", "Fantasy", "Drama"],
        cast: ["Peter Dinklage", "Lena Headey", "Kit Harington"],
      },
      {
        title: "Chernobyl",
        thumbnail: "/images/chernobyl-thub.jpg",
        slug: "chernobyl",
        desc: "Černobyl, pětidílná minisérie z koprodukce společností HBO a Sky, rekonstruuje příběh o jaderné havárii z roku 1986, jedné z nejhorších katastrof v historii způsobených člověkem, a o obětech, které byly učiněny pro záchranu Evropy před nepředstavitelnou pohromou. Dne 26. dubna 1986 otřásla jadernou elektrárnou v Černobylu na Ukrajině mohutná exploze, která uvolnila nebezpečné radioaktivní látky nejen na ukrajinském, běloruském a ruském území tehdejšího Sovětského svazu, ale také do oblastí Skandinávie a západní Evropy. Jared Harris ztvárňuje Valerije Legasova, předního sovětského jaderného fyzika, který vedl vyšetřování tragické události. Stellan Skarsgård hraje sovětského místopředsedu vlády Borise Ščerbinu, kterého Kreml pověřil vedením vládní komise zjišťující okolnosti havárie. Emily Watsonová představuje jadernou fyzičku Ulanu Khomyukovou, která chce odhalit tajemství kolem černobylského neštěstí. ",
        release: "2019",
        categories: ["Akční", "Drama", "Thriller"],
        cast: ["Jared Harris", "Stellan Skarsgård", "Emily Watson"],
      },
      {
        title: "The Last of Us",
        thumbnail: "/images/last-thub.webp",
        slug: "the-last-of-us",
        desc: "Dvacet let po zániku moderní civilizace je otrlý přeživší Joel najat, aby propašoval čtrnáctiletou Ellie z nebezpečné karanténní zóny. Oba se musí vydat na cestu napříč Spojenými státy a spoléhat jeden na druhého, aby přežili.",
        release: "2023",
        categories: ["Akční", "Dobrodružný", "Drama"],
        cast: ["Bella Ramsey", "Pedro Pascal", "Gabriel Lunas"],
      },
    ],
  },
  {
    name: "primevideo",
    color: "#4C4C4C",
    image: "/images/primevideo.jpg",
    cover: "/images/amazon-prime-cover.jpg",
    series: [
      {
        title: "The Boys",
        thumbnail: "/images/boys-thub.jpg",
        slug: "the-boys",
        desc: "Seriál The Boys, adaptován z komiksové předlohy stejného názvu a vytvořen hercem a režisérem Sethem Rogenem, je zasazen do alternativního vesmíru, kde jednotlivci obdaření supermocí jsou uznáváni širokou veřejností jako superhrdinové. Tyto superhrdiny vlastní silná společnost Vought International, která je prodává a zpeněžuje. Tito superhrdinové se ve svém osobním životě chovají arogantně a rádi zneužívají svoje superschopnosti. Seriál sleduje primárně dvě skupiny: Sedm, neboli přední tým superhrdinů Vought International a skupinu The Boys, která se snaží zničit tyto zkorumpované superhrdiny. Skupina The Boys je vedena Billym Butcherem (Karl Urban), který nenávidí všechny superhrdiny a skupina Sedm je vedena egoistickým a nestabilním Homelanderem (Antony Starr). Mimo jejich konflikt sleduje seriál také nové členy každého týmu: Hugh Hughie Campbell (Jack Quaid), který se přidá ke skupině The Boys hned poté, co jeho přítelkyně je zabita jedním ze skupiny Sedm, a Annie January/Starlight (Erin Moriarty), která se přidá do skupiny Sedm, ale v zápětí zjišťuje, že superhrdiny, které obdivovala, se nechovají tak, jak si představovala.",
        release: "2019",
        categories: ["Akční", "Komedie ", "Drama"],
        cast: ["Karl Urban", "Jennifer Esposito", "Jack Quaid"],
      },
      {
        title: "The Legend of Vox Machina",
        slug: "the-legend-of-vox-machina",
        thumbnail: "/images/vox-thub.png",
        desc: "Je to drsná parta ztracených existencí, z nichž se stali nájemní žoldnéři. Vox Machina se zajímá spíš o snadný výdělek a levné pivo než o ochranu země. Když však království ohrožuje zlo, naše divoká parta si uvědomí, že jedině oni jsou schopni znovu nastolit spravedlnost. Co začalo jako jednoduchá fuška, je nyní příběhem o původu nejnovějších hrdinů Exandrie. ",
        release: "2022",
        categories: ["Animovaný", "Dobrodružný", "Drama"],
        cast: ["Matthew Mercer", "Ashley Johnson", "Laura Bailey"],
      },
      {
        title: "The Lord of the Rings: The Rings of Power",
        thumbnail: "/images/rings-thub.jpg",
        slug: "the-lord-of-the-rings-the-rings-of-power",
        desc: "Začínáme dobou relativního míru a sledujeme společenství postav, které čelí znovuobjevení zla ve Středozemi. Od nejtemnějších hlubin Mlžných hor přes majestátní lesy Lindonu, dechberoucí ostrovní království Númenor, až po nejzazší kouty mapy, stvoří tato království a postavy dědictví, která přežívají ještě dlouho po jejich odchodu. ",
        release: "2022",
        categories: ["Akční", "Dobrodružný", "Fantasy"],
        cast: ["Morfydd Clark", "Robert Aramayo", "Ismael Cruz Cordova"],
      },
    ],
  },
];

export const user = [
  {
    name: "profile",
    color: "#4C4158",
    image: "/images/user.webp",
  },
];
